---

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    update_cache: yes

- name: Add repo key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add docker.io repo
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable' state=present

- name: Install docker
  apt: name=docker-ce update_cache=yes force=yes

- apt: name=python-docker

- name: Assemble daemon config
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json
  notify: "restart docker service"
