---

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python-pip
    update_cache: yes

- name: Add repo key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add docker.io repo
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable' state=present

- name: Install docker
  apt: name=docker-ce update_cache=yes force=yes

- name: Assemble daemon config
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json
  notify: "restart docker service"

- name: Install python library
  pip: name=docker

- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.21.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
    checksum: sha256:8a11713e11ed73abcb3feb88cd8b5674b3320ba33b22b2ba37915b4ecffdf042
