---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
