name: Tests

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install requirements
        run: pip install tox

      - name: Run tests
        run: tox
